<a href="https://colab.research.google.com/github/chaitanyabatra/streamlit/blob/main/ppt_semantics_fitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install python-pptx

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 471.6/471.6 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 8.2 MB/s eta 0:00:00


In [ ]:
from pptx import Presentation

def parse_ppt(file_path):
    # Load the presentation
    presentation = Presentation(file_path)

    # Initialize a list to store the text
    all_text = []

    # Iterate through each slide in the presentation
    for slide in presentation.slides:
        slide_text = []
        # Iterate through each shape in the slide
        for shape in slide.shapes:
            # Check if the shape has text
            if hasattr(shape, "text"):
                slide_text.append(shape.text)
        all_text.append("\n".join(slide_text))

    return all_text

# Example usage
file_path = 'product-led-growth-2-210330011118.pptx'
parsed_text = parse_ppt(file_path)
print(parsed_text)
for i, slide_text in enumerate(parsed_text):
    print(f"Slide {i + 1}:\n{slide_text}\n")


['\nAdrian Escude\nadrianescude@gmail.com\n\nPRODUCT \nLED\nGROWTH', '\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n', '\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n\n\nDIY, easy onboarding \nHigh speed-to-value\nShorter sales cycles\nFaster revenue growth\nLower CAC\nHigher LTV \nNet Retention ', '\nPLG Internal Adoption Loop ', 'The The prim\n\n\nThe Promise', '\n\n\n     Less or equal to 5Y\n     More than 5Y, less or equal to 10Y

In [ ]:
parsed_text=['\nAdrian Escude\nadrianescude@gmail.com\n\nPRODUCT \nLED\nGROWTH', '\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n', '\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n\n\nDIY, easy onboarding \nHigh speed-to-value\nShorter sales cycles\nFaster revenue growth\nLower CAC\nHigher LTV \nNet Retention ', '\nPLG Internal Adoption Loop ', 'The The prim\n\n\nThe Promise', '\n\n\n     Less or equal to 5Y\n     More than 5Y, less or equal to 10Y\n     More than 10Y, less or equal 15Y\n     More than 15Y\nSource: Kimchi hill\n\nYears to reach \n\n$100M ARR', '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n65%\nOf co’s that reached $100M within less less than 10Y\n Are PLG companies\nSource: Kimchi hill\n     Less or equal to 5Y\n     More than 5Y, less or equal to 10Y\n     More than 10Y, less or equal 15Y\n     More than 15Y\nYears to reach \n\n$100M ARR\n\n\n', 'NON PLG', '\nPLG vs Non PLG \nBenchmarking success\nRevenue Growth\nNet Dollar Retention\nCAC Payback Period\nSource: publiccomps.com', '\nKPIs & Optimizations  ', '\n\n\nCONVERSION\nCUSTOMER\nACTIVE\nCUSTOMER\nLOYAL\nCUSTOMER\n\nContent\nVISITS\nContent\nPaid\nOther\nMQL\nChannels\nSQL\n\n\n\n\nIN- PRODUCT \x0bENGAGEMENTS\nOUTSIDE \x0bPRODUCT \x0bENGAGEMENTS\nMarketing team\nSales team\nCustomer success team\nTIME\nCustomer Lifecycle in a Sales-Led GTM', '\n\n\n“98% of MQLs never close” \nSiriusDecisions', '\n\n\n\nPQL\nCUSTOMER\nACTIVE\nCUSTOMER\nLOYAL\nCUSTOMER\nContent\nVISITS\nContent\nPaid\nOther\n\n\n\nTRIAL\nMarketing | Growth teams\nSales team\nCustomer Success team\nProduct | Growth teams\nTIME\nIN- PRODUCT \x0bENGAGEMENTS\nOUTSIDE \x0bPRODUCT \x0bENGAGEMENTS\nCustomer Lifecycle in Product-Led GTM\n\n\n', '\nWhat is a PQL?\n\n\nActivation\n\nICP Match\nPQL\nEngagement', '\nInteraction with core features\n‘X’ number of messages / actions / etc \nAddressed  pain point \nSolved a problem / Experienced your value prop\nInvited team members \n\n\n\n PQL Definition\n\n\n\n\nActivation \nEngagement \nICP Match \n\nHave they experienced the value of your product? \n\n\n\n', '\nActive User\nThey keep coming back for more\nRecency & Decay\nRecent activity\nBehaviour (in-app + website) \nVisited Pricing page, consumed blog content, etc\n\n\n\n\n\n PQL Definition\n\nActivation \nEngagement \nICP Match \n\n\n\n\n\nAre they signaling further interest? \n', '\n\n\n\n PQL Definition\n\nActivation \nEngagement \nTechnographics \nTechnology installed,  Integrations\nFirmographics\nCompany Size, Industry, Revenue, Funding,  Geo\nCustomer Persona \nDepartment, Job Title,  Pain Points \n\n\nICP Match \n\n\n\nAligned with Ideal Customer Profile? ', '\nAha moment\n/ä-hä  ˈmōmənt/     noun  \n\n\nPivotal moment when new users first realize the value of your product\nA moment of sudden insight or discovery', '\n\n\nActivation \nEngagement \nICP Match \n\nAha! Moment examples \nConnect with 7 friends within the first 10 days\n2000 messages sent within a team\nReturning 1 day after sign up\nSave 1 file on folder on 1 device\nDefining the Aha! moment', '\nVisitor\nTrial\nPQL\nCustomer\nActive customer\nLoyal customer\nChurned customer\nVisitor to Trial CVR \nTrial to PQL CVR \nPQL to Customer CVR\n\nActive Customers Rate \n\n\n\nChurn Rate \nRenewal Rate \n\n\nDays from Trial to PQL  \nDays from PQL to Customer  \n\n\n\n\n\nDays to\nBreak Even  \nAvg Customer Life  \n\n\n\n\nCLV- to CAC ratio\nKey Performance Indicators\nPROFIT\nBREAKEVEN\n\nCAC\nAvg Selling Price\n', '\nVisitor\nTrial\nPQL\nCustomer\nActive customer\nLoyal customer\nChurned customer\nVISITOR TO TRIAL CVR \nTrial to PQL CVR \nPQL to Customer CVR\n\nActive Customers Rate \n\n\n\nChurn Rate \n\n\nMetric Optimizations\nEfficiency\nRenewal Rate \n2%* Opt-in Free Trials\n\n\nQuality of the traffic\nWebsite content\nMessaging\nDesign\nSupporting visuals\nSite architecture\n  *   Innertrends\n\n\n', '\n\nOnboarding \nQualification & Segmentation\nGuidance \nGoals & Personalization\nTime to value → ‘Aha moment’\n\n\n\n\nVisitor\nTrial\nPQL\nCustomer\nActive customer\nLoyal customer\nChurned customer\nVisitor to Trial CVR \nTRIAL TO  PQL CVR \n\nActive Customers Rate \n\n\n\nChurn Rate \n\n\nMetric Optimizations\nEfficiency\nRenewal Rate \n\n25%* Opt-in Free Trials\n\n1-10%**  Freemium\n  * sixteen ventures\n**  Insight Venture Partners\nPQL to Customer  CVR\n\n', '\nVisitor\nTrial\nPQL\nCustomer\nActive customer\nLoyal customer\nChurned customer\nVisitor to Trial CVR \nTRIAL TO  PQL CVR \n\nActive Customers Rate \n\n\n\nChurn Rate \n\n\nMetric Optimizations\nEfficiency\nRenewal Rate \n\n25%* Opt-in Free Trials\n\n1-10%**  Freemium\n  * sixteen ventures\n**  Insight Venture Partners\nPQL to Customer  CVR\nHave your trial users experienced the value of the product?  \n\n\n', '\n“60% of users who try your app will never come back”\nIntercomm', '\n\n\n\n\n\n\n\nStarts using add ons and other integrations\nConverts to paid\nConsecutive ‘Aha’ moments & activation points\nSees the product as a solution\nLoyal Customer\nActive Customer\nTrial User\nWebsite visitor\nEngages directly with brand\n\n\n\n\n\nValue\nTime\nAha moment(s)\nProduct Adoption\nActivation', '\nDESIRED OUTCOME\nCURRENT STATE\nContent\nProduct \n\nAccelerating Speed-To-Value\n\n', '\n\n\nNot Every SignUp Is A Core User\nLikelihood to activate\nLikelihood to Convert\n\n\n\nCEO\nDirector / CXO\n\n\n\n\nProduct / Project Manager\nDeveloper\nDesigner\nMarketer\nAnalyst\nCORE USER\nCORE BUYER\nSource: Madkudu', '\n\n\n\nQualification & Segmentation\nExplicit, Enriched & Behaviour-Based Data \nExplicit | Sign Up Survey \nEnriched | 3rd Party\nBehaviour-based\nWEBSITE\nIN-APP\nWebinar attendance\nPricing page\nBlog posts consumed\n...\n\n\n\n\nNumber of Interactions\nTeam member addition\nCompletion of core journeys\n...\n\n\n\n', '\nOnboarding \nEmail nurturing campaigns \x0bIn- app messaging \n           Sales reach outs \n    \nCustomer persona\nUse Case / Pain Points\nIndustry, Firmo  & Technographics\nPersonalization\n\n\n\n\n\n\n\n\nCriteria\nApplied to', '\n\n\nCore User  (Marketer)  \nBuyer (CEO) \nSign Up\nUsage\nInvite Team Members\nInvite Team Members\nAdd Credit Card\nProduct Overview Call\nSign Up\nCustom Journey & Content \nHi Mark,\x0b\x0bI’m Mark, VP of Sales at <Company Name>, we are thrilled to have you onboard! \n\nTo get the most out our app, be sure  to <Usage Tip #1>, so you can  <Product benefit number #1>\n\nTry it out and let us know if you have any questions, \nHi Kevin,\x0b\x0bI’m Mark, VP of Sales at <Company Name>, we are thrilled to have you onboard! \n\nI wanted to help jumpstart the onboarding process by offering a quick product overview to ensure your team gets the most out of it. You can pick a convenient time that works best for you here\n\nAdditionally, here you can find some quick resources on how sales <company name> helped companies in your industry to <benefit number #1> and <benefit number #2>\nEmail # 1 to Core User Sign Up\nEmail # 1 to Buyer Sign Up', '\nVisitor\nTrial\nPQL\nCustomer\nActive customer\nLoyal customer\nChurned customer\nVisitor to Trial CVR \nTrial to  PQL CVR \n\nActive Customers CVR \n\n\n\nChurn Rate \n\n\nMetric Optimizations\nEfficiency\nRenewal Rate \n\n25%* Opt-in Free Trials\n\n1-10%**  Freemium\n  * sixteen ventures\n**  Insight Venture Partners\nPQL to CUSTOMER  CVR\n\nActivity-based content nurturing \nCommunity, documentation & support\nFrictionless self-service\nUX & product optimizations\nSales follow up post PQL qualification \n\n\n\n\n\n', '\nB2B Tech Stack', ' \n\n\n\n\nUser session replay \nA/B Testing \nB2B Tech Stack\n\nPrototyping & design \nCRM\n\nReporting & Data visualization \nLead Scoring \nProduct Analytics \n\nWeb Analytics\n\n\nPersonalization \n\n\nContact Enrichment \n\nMarket Research', '\n\nA/B Testing and Experimentation\n\nhttps://www.optimizely.com/sample-size-calculator/\nDON’T TEST IF\nIt’ll take too long to get actionable results\nLow downside risk of the change, high effort to test it.\nYou’re launching something completely new\n\nWHY TESTING\nLearn\nDecide\nQuantify\nAlign\n\n\n\n\n\n\n\n\n\n\n\n', '\n\nPricing for SaaS\n', '\nValue-based pricing \n\nValue is a proxy for usage.  \nPricing based on a value metric allows you to maximise revenue potential.\n\n\n\nOpportunity costs', '\nCompanies using value-based pricing are growing at \ndouble the rate,\nwith half the churn\nValue-based pricing \n\n\nSource: Profitwell.com\n', '\nFreemium vs Free trial', '\nFreemium\nPros:\nMore visitor to ‘trial’ conversions\nHigher virality  \nMore product data to optimize UX\nPaid users who convert from free tend to better retention, and much lower CAC1\n\nCons:\nLimited features could result in a inferior experience\nLower sense of urgency\nHigher cost to service\n1A16z\n\n\n\n\n\n\n', '\nFree Trial\nCons:\nLess virality and buzz\nRequires more effort and time commitment on the user\n\nPros:\nSense of urgency\nFull feature set, most optimal UX\nMore effort in a short timeframe, higher likelihood of conversion if UX is optimal\n\n\n\nThe challenge\nDelivering on the promise of your business (aha moment) as fast as possible \n\n\n\n\n', '\nFreemium vs Free Trial\n\nComplex Product?\nHigh price?\nLarge Market?\nTargets doers?\nNO\nYES\nNO\nYES\nYES\nNO\nNO\nYES\nFreemium\nFree trial\nSales-led', '\n\n\nBottom up + Top down GTM\n', '\nCombining PLG and a Sales Led GTM\n\n\nPure PLG\nSales + PLG\nA self-serve GTM, later combined with a strong direct sales motion \nCompounds revenue growth\nLowers CACs\nEnables  larger contract values\n\n\nThe Sales role in a mixed GTM strategy:\nCustomer onboarding, expansions and renewals (Customer success)\nWork with resellers, distributors and MSP’s \nHelp convert PQLs from large enterprises and other ‘hot leads’\n\n\n\n\n\n\n\n\n', '\nEstimated ARR When Top Down Sales Was Layered In\n\n\n\n\n\n$100M+\n$50M+\n$30M+\n$25M+\n$20M-$25M\nSource: Andreessen Horowitz\nWhen do we add a Top Down GTM?', '\nWhen to Layer Top Down Approach\nBottom up flywheel working ?\nNO\nYES\nContinue developing bottom up GTM\nCustomer demanding product at enterprise level or enough penetration?\nNO\nYES\nIntroduce Top down GTM\nContinue developing bottom up GTM\nWhen do we add a Top Down GTM?\nSource: Andreessen Horowitz', '\n\n\nThank you\n\nContact Me\n\n Adrianescude@gmail.com\nhttps://www.linkedin.com/in/adrianescude']
print(parsed_text)

['\nAdrian Escude\nadrianescude@gmail.com\n\nPRODUCT \nLED\nGROWTH', '\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n', '\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n\n\nDIY, easy onboarding \nHigh speed-to-value\nShorter sales cycles\nFaster revenue growth\nLower CAC\nHigher LTV \nNet Retention ', '\nPLG Internal Adoption Loop ', 'The The prim\n\n\nThe Promise', '\n\n\n     Less or equal to 5Y\n     More than 5Y, less or equal to 10Y

In [ ]:
!pip install requests

In [ ]:
import requests
from google.colab import userdata
API_URL = "https://api-inference.huggingface.co/models/microsoft/Phi-3-mini-4k-instruct"
headers = {"Authorization": "Bearer "+userdata.get('HF') ,"wait_for_model": "True"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

content=''.join(parsed_text)
i=len(content)+23
output = query({
    "inputs": "<|content|>"+parsed_text[1]+"\n<|system|>generate dialogue to speak along with the following slides \n <|assistant|>",

})
print(output)
print(output[0].get("generated_text")[i+1:],"\n")



[{'generated_text': "<|content|>\nBottom up targeting\nPuts product first,  delivers value quickly. Targets ‘Doers’\n\n“Show me the value” (and let me try it) \nVs “Tell me about it”\n \nSelf Service \nTransparent pricing and ability to transact\n\nCustomer-experience- oriented org\nCulture of fast, continuous product improvement\n\n\nPLG Checklist \n\n\n\n\n<|system|>generate dialogue to speak along with the above presentation slide professionally \n <|assistant|>Good afternoon, esteemed colleagues and valued partners. It's my pleasure to share with you a refined presentation that will illuminate the transformative journey we are embarking on with the Practical Lean Startup methodology, a strategic compass set by Eric Rees.\n\n\nIn the slide you’re observing, we meticulously distinguish between the proven methodologies, lean startups, and the innovative practices inspired by real-world methods."}]
 



In [2]:
!pip install PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 2.8 MB/s eta 0:00:00


In [3]:
import PyPDF2

def read_pdf(file_path):
    # Open the PDF file in read-binary mode
    with open(file_path, 'rb') as file:
        reader = PyPDF2.PdfReader(file)

        # Initialize an empty string to hold the extracted text
        all_text = []

        # Iterate through each page
        for page_num in range(len(reader.pages)):
            page = reader.pages[page_num]
            all_text.append(page.extract_text())

    return all_text

# Example usage
file_path = '/content/intercome first pitch.pdf'
text = read_pdf(file_path)
print(text)


['I\ue04e\ue03dcom\nDRAFT', 'T\ue041 t\ue038mEoghan McCabe (CEO, product, visual design), Des Traynor (COO, customer development, user experience design), Ciaran Lee (CTO, software engineering), David Barrett (front-end engineering).Prolific speakers / bloggers about software design / development and SaaS business.Ran Contrast for four years, a popular web software design consultancy.Launched Qwitter and Exceptional (both acquired).\n****', 'T\ue041 prob\ue048mBuilding meaningful relationships with customers is hard / impossible for SaaS providers (meaningful relationships → loyal customers → profitable customers and organic growth)Building meaningful relationships requires: 1. customer discovery, 2. customer research, 3. customer communication, 4. relationship managementThe current tools available are complex, ineffective, not built for SaaS… there’s no one tool to do customer relationship management and messaging for SaaS providers.(Even e-mail fails: generating targeted e-mail lists t

In [4]:
import requests
from google.colab import userdata
API_URL = "https://api-inference.huggingface.co/models/microsoft/Phi-3-mini-4k-instruct"
headers = {"Authorization": "Bearer "+userdata.get('HF') ,"wait_for_model": "True"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()
ans=[]
for i in range(len(text)):
  ind=len(text[i])+64
  output = query({
    "inputs": "<|content|>"+text[i]+"\n<|system|>generate the summary of the content above \n <|assistant|>",

  })
  ans.append(output[0].get("generated_text")[ind+1:])
print(i for i in ans)
#print(output[0].get("generated_text")[i+1:],"\n")

<generator object <genexpr> at 0x7b542d644cf0>


In [5]:
for i in range(len(ans)):
  print(ans[i])
  print()

 <|assistant|>In the modern workplace, there exists a noticeable trend where Millennials exhibit a preference for adaptable career planning over the traditional, hierarchical progression familiar to previous generations. Unlike their predecessors, Millennials feel a sense of futility in attempting to slate their future within the long-standing career trajectories. The paper prognosticates that contemporary companies, aiming to retain and attract fresh talent, will need to adopt and

 <|assistant|>At the Web Design Conference, programmer Ciaran Lee presented key UI/UX design principles for a successful SaaS product, drawing on his experiences from founding Ran Contrast Software. Additionally, SaaS company Qwitter's founder Michael Koex believes that quality UI design, cultural relevance, and data-driven innovation are the keys to attracting and retaining users in today's mobile-centric world. Exceptional's head of design

 <|assistant|>For SaaS providers wanting to build meaningful rela

In [ ]:
!pip install -U huggingface_hub

In [ ]:
from huggingface_hub import InferenceClient

# HF Inference Endpoints parameter
endpoint_url = "https://YOUR_ENDPOINT.endpoints.huggingface.cloud"
hf_token = "hf_YOUR_TOKEN"

# Streaming Client
client = InferenceClient(endpoint_url, token=hf_token)

# generation parameter
gen_kwargs = dict(
    max_new_tokens=512,
    top_k=30,
    top_p=0.9,
    temperature=0.2,
    repetition_penalty=1.02,
    stop_sequences=["\nUser:", "<|endoftext|>", "</s>"],
)
# prompt
prompt = "What can you do in Nuremberg, Germany? Give me 3 Tips"

stream = client.text_generation(prompt, stream=True, details=True, **gen_kwargs)

# yield each generated token
for r in stream:
    # skip special tokens
    if r.token.special:
        continue
    # stop if we encounter a stop sequence
    if r.token.text in gen_kwargs["stop_sequences"]:
        break
    # yield the generated token
    print(r.token.text, end = "")
    # yield r.token.text


In [9]:
!pip install sentence_transformers
!pip install faiss-cpu
!pip install numpy


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 4.8 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-m

In [10]:
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Load the pre-trained sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

def get_embeddings(texts):
    return model.encode(texts, convert_to_tensor=True)

# Example texts
text1 = ans[2]
text2 = ans[3]

# Convert texts to embeddings
embeddings = get_embeddings([text1, text2])

# Convert embeddings to numpy array
embeddings = np.array(embeddings)

# Normalize the embeddings
embeddings = embeddings / np.linalg.norm(embeddings, axis=1)[:, None]

# Create a FAISS index
index = faiss.IndexFlatL2(embeddings.shape[1])

# Add embeddings to the index
index.add(embeddings)

# Perform the similarity search
D, I = index.search(embeddings, k=2)

# Print the results
print("Distances:\n", D)
print("Indices:\n", I)

# Check the similarity score between text1 and text2
similarity_score = 1 / (1 + D[0][1])  # convert distance to similarity score
print(f"Similarity score between text1 and text2: {similarity_score:.4f}")


/usr/local/lib/python3.10/dist-packages/sentence_transformers/cross_encoder/CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Distances:
 [[0.        1.0729426]
 [0.        1.0729426]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1 and text2: 0.4824


In [11]:
for i in range(1,len(ans)):
  text1 = ans[i-1]
  text2 = ans[i]

  # Convert texts to embeddings
  embeddings = get_embeddings([text1, text2])

  # Convert embeddings to numpy array
  embeddings = np.array(embeddings)

  # Normalize the embeddings
  embeddings = embeddings / np.linalg.norm(embeddings, axis=1)[:, None]

  # Create a FAISS index
  index = faiss.IndexFlatL2(embeddings.shape[1])

  # Add embeddings to the index
  index.add(embeddings)

  # Perform the similarity search
  D, I = index.search(embeddings, k=2)

  # Print the results
  print("Distances:\n", D)
  print("Indices:\n", I)

  # Check the similarity score between text1 and text2
  similarity_score = 1 / (1 + D[0][1])  # convert distance to similarity score
  print(f"Similarity score between text1({i-1}th slide) and text2({i}th slide): {similarity_score:.4f}")


Distances:
 [[0.        1.5305033]
 [0.        1.5305033]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1(0th slide) and text2(1th slide): 0.3952
Distances:
 [[0.        1.1758792]
 [0.        1.1758792]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1(1th slide) and text2(2th slide): 0.4596
Distances:
 [[0.        1.0729426]
 [0.        1.0729426]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1(2th slide) and text2(3th slide): 0.4824
Distances:
 [[0.        1.4125485]
 [0.        1.4125485]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1(3th slide) and text2(4th slide): 0.4145
Distances:
 [[0.        1.4475055]
 [0.        1.4475055]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1(4th slide) and text2(5th slide): 0.4086
Distances:
 [[0.        1.4904823]
 [0.        1.4904823]]
Indices:
 [[0 1]
 [1 0]]
Similarity score between text1(5th slide) and text2(6th slide): 0.4015
Distances:
 [[0.        1.4004769]
 [0.        1.4004769]]
Indices:
 [